services:
  chroma-server:
    image: chromadb/chroma
    container_name: chroma-dados-rag
    network_mode: "host"
    volumes:
      - ./chroma_db:/chroma/chroma

  rag-api:
    build: .
    container_name: rag-api-service
    network_mode: "host"
    env_file:
      - .env
    depends_on:
      - chroma-server
